#define KEY_Esc                         027
#define KEY_1                           049
#define KEY_2                           050
#define KEY_3                           051
#define KEY_4                           052
#define KEY_5                           053
#define KEY_6                           054
#define KEY_7                           055
#define KEY_8                           056
#define KEY_9                           057
#define KEY_0                           048
#define KEY_Minus                       045
#define KEY_Equal                       061
#define KEY_Backspace                   008
#define KEY_Tab                         009
#define KEY_q                           113
#define KEY_w                           119
#define KEY_e                           101
#define KEY_r                           114
#define KEY_t                           116
#define KEY_y                           121
#define KEY_u                           117
#define KEY_i                           105
#define KEY_o                           111
#define KEY_p                           112
#define KEY_Left_Bracket                091
#define KEY_Right_Bracket               093
#define KEY_Enter                       013
#define KEY_a                           097
#define KEY_s                           115
#define KEY_d                           100
#define KEY_f                           102
#define KEY_g                           103
#define KEY_h                           104
#define KEY_j                           106
#define KEY_k                           107
#define KEY_l                           108
#define KEY_Semicolon                   059
#define KEY_Apostrophe                  039
#define KEY_Backtick                    096
#define KEY_Backslash                   092
#define KEY_z                           122
#define KEY_x                           120
#define KEY_c                           099
#define KEY_v                           118
#define KEY_b                           098
#define KEY_n                           110
#define KEY_m                           109
#define KEY_Comma                       044
#define KEY_Period                      046
#define KEY_Slash                       047
#define KEY_Space                       032
#define KEY_F1                          059 // Extended
#define KEY_F2                          060 // Extended
#define KEY_F3                          061 // Extended
#define KEY_F4                          062 // Extended
#define KEY_F5                          063 // Extended
#define KEY_F6                          064 // Extended
#define KEY_F7                          065 // Extended
#define KEY_F8                          066 // Extended
#define KEY_F9                          067 // Extended
#define KEY_F10                         068 // Extended
#define KEY_F11                         133 // Extended
#define KEY_F12                         134 // Extended
#define KEY_Home                        071 // Extended
#define KEY_Up_Arrow                    072 // Extended
#define KEY_Page_Up                     073 // Extended
#define KEY_Left_Arrow                  075 // Extended
#define KEY_Center_Key                  076 // Extended
#define KEY_Right_Arrow                 077 // Extended
#define KEY_End                         079 // Extended
#define KEY_Down_Arrow                  080 // Extended
#define KEY_Page_Down                   081 // Extended
#define KEY_Insert                      082 // Extended
#define KEY_Delete                      083 // Extended
#define KEY_Exclamation                 033
#define KEY_At                          064
#define KEY_Hash                        035
#define KEY_Dollar                      036
#define KEY_Percent                     037
#define KEY_Carat                       094
#define KEY_And                         038
#define KEY_Asterisk                    042
#define KEY_Left_Parentheses            040
#define KEY_Right_Parentheses           041
#define KEY_Underscore                  095
#define KEY_Plus                        043
#define KEY_Shift_Tab                   015 // Extended
#define KEY_Q                           081
#define KEY_W                           087
#define KEY_E                           069
#define KEY_R                           082
#define KEY_T                           084
#define KEY_Y                           089
#define KEY_U                           085
#define KEY_I                           073
#define KEY_O                           079
#define KEY_P                           080
#define KEY_Left_Brace                  123
#define KEY_Right_Brace                 125
#define KEY_A                           065
#define KEY_S                           083
#define KEY_D                           068
#define KEY_F                           070
#define KEY_G                           071
#define KEY_H                           072
#define KEY_J                           074
#define KEY_K                           075
#define KEY_L                           076
#define KEY_Colon                       058
#define KEY_Quotation                   034
#define KEY_Tilde                       126
#define KEY_Pipe                        124
#define KEY_Z                           090
#define KEY_X                           088
#define KEY_C                           067
#define KEY_V                           086
#define KEY_B                           066
#define KEY_N                           078
#define KEY_M                           077
#define KEY_Left_Angle                  060
#define KEY_Right_Angle                 062
#define KEY_Question                    063
